version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: superdbuser
      POSTGRES_PASSWORD: Java_123
      POSTGRES_DB: blaise_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:6
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "8088:8088" 
    depends_on:
      - db
      - redis
    networks:
      - backend

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.routes worker --concurrency=10 --loglevel=info -Q app2_queue
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
