"""adding more fields

Revision ID: 1e75d761438b
Revises: 9667880a0a84
Create Date: 2024-10-05 20:12:27.578178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e75d761438b'
down_revision: Union[str, None] = '9667880a0a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_info', sa.Column('user_input_origin', sa.String(length=50), nullable=False))
    op.add_column('flight_info', sa.Column('user_input_destination', sa.String(length=50), nullable=False))
    op.add_column('flight_info', sa.Column('start_date', sa.String(length=50), nullable=False))
    op.add_column('flight_info', sa.Column('end_date', sa.String(length=50), nullable=False))
    op.add_column('flight_info', sa.Column('flight_unique_field', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_info', 'flight_unique_field')
    op.drop_column('flight_info', 'end_date')
    op.drop_column('flight_info', 'start_date')
    op.drop_column('flight_info', 'user_input_destination')
    op.drop_column('flight_info', 'user_input_origin')
    # ### end Alembic commands ###
