"""initial_required_models

Revision ID: 61368626e30a
Revises: 
Create Date: 2024-10-10 09:02:22.225664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61368626e30a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_destination', sa.String(length=100), nullable=False),
    sa.Column('end_destination', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.String(length=25), nullable=False),
    sa.Column('arrival_time', sa.String(length=25), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('stops', sa.String(length=200), nullable=True),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('economy_class', sa.String(length=50), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('flight_link', sa.Text(), nullable=True),
    sa.Column('user_input_origin', sa.String(length=50), nullable=False),
    sa.Column('user_input_destination', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('flight_unique_field', sa.String(length=250), nullable=False),
    sa.Column('source_website', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.String(length=50), nullable=False),
    sa.Column('islogin', sa.Boolean(), nullable=False),
    sa.Column('isauthenticated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_table('flight_booking_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('start_destination', sa.String(length=100), nullable=False),
    sa.Column('end_destination', sa.String(length=100), nullable=False),
    sa.Column('start_destination_country', sa.String(length=100), nullable=False),
    sa.Column('end_destination_country', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.String(length=100), nullable=False),
    sa.Column('end_date', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_id'), 'verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_verification_tokens_token'), 'verification_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_tokens_token'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_id'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_table('flight_booking_info')
    op.drop_table('user_info')
    op.drop_table('flight_info')
    # ### end Alembic commands ###
