"""adding user and flight_booking

Revision ID: 65735ba4519a
Revises: ee48630a4309
Create Date: 2024-10-05 10:18:14.381675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65735ba4519a'
down_revision: Union[str, None] = 'ee48630a4309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_booking_info')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_booking_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_destination', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('end_destination', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('end_destination_country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='flight_booking_info_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='flight_booking_info_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email_id', name='user_email_id_key')
    )
    # ### end Alembic commands ###
