"""adding user and flight_booking

Revision ID: 9667880a0a84
Revises: 65735ba4519a
Create Date: 2024-10-05 10:19:15.062103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9667880a0a84'
down_revision: Union[str, None] = '65735ba4519a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_table('flight_booking_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_destination', sa.String(length=100), nullable=False),
    sa.Column('end_destination', sa.String(length=100), nullable=False),
    sa.Column('start_destination_country', sa.String(length=100), nullable=False),
    sa.Column('end_destination_country', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.String(length=100), nullable=False),
    sa.Column('end_date', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_booking_info')
    op.drop_table('user_info')
    # ### end Alembic commands ###
