"""adding names

Revision ID: d116a9c6615d
Revises: 67c8b27f2b33
Create Date: 2024-10-07 05:54:20.073583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd116a9c6615d'
down_revision: Union[str, None] = '67c8b27f2b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_booking_info', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('flight_booking_info', sa.Column('last_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_booking_info', 'last_name')
    op.drop_column('flight_booking_info', 'first_name')
    # ### end Alembic commands ###
