"""initial_migrations

Revision ID: da0cd1800487
Revises: 
Create Date: 2024-09-28 11:48:39.516186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0cd1800487'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_destination', sa.String(length=100), nullable=False),
    sa.Column('end_destination', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.String(length=25), nullable=False),
    sa.Column('arrival_time', sa.String(length=25), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('stops', sa.String(length=200), nullable=True),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('economy_class', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('flight_link', sa.Text(), nullable=True),
    sa.Column('source_website', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_info')
    # ### end Alembic commands ###
