"""addingcomplete proffile

Revision ID: eed71f25f2c9
Revises: 61368626e30a
Create Date: 2024-10-11 09:00:55.940129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed71f25f2c9'
down_revision: Union[str, None] = '61368626e30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('isprofilecompleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'isprofilecompleted')
    # ### end Alembic commands ###
