"""adding user and flight_booking

Revision ID: f3fffcc7c127
Revises: 064c0eb3da63
Create Date: 2024-10-05 09:49:36.112591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3fffcc7c127'
down_revision: Union[str, None] = '064c0eb3da63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_table('flight_booking_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_destination', sa.String(length=100), nullable=False),
    sa.Column('end_destination', sa.String(length=100), nullable=False),
    sa.Column('start_destination_country', sa.String(length=100), nullable=False),
    sa.Column('end_destination_country', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.String(length=100), nullable=False),
    sa.Column('end_date', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_booking_info')
    op.drop_table('user')
    # ### end Alembic commands ###
